# Generates the outcome of a response surface given beta
# x_data is the x variables generated by gen_response_surface_x
# beta is the a vector of regression coefficients ordered in the same way as x_data c(linear_x1, linear_x2, quad_x1, quad_x2, int_x1_x2)
# sigma is the residual standard deviation
# y_name allows you to name the outcome variable something meaningful. 

gen_response_surf_y<-function(x_data, beta, sigma=NULL, y_name=NULL){
  
  if(is.null(y_name)){
    y_name<-"y"
  }
  
  if(is.null(sigma)){
    eps<-0
  }else{
    eps<-rnorm(nrow(x_data), 0, sigma)
  }
  
  x_data[y_name]<-as.vector(as.matrix(x_data)%*%beta+eps)
  
}
