# Given an object generated by t-test quiz saved as an RDS, creates a parameterized rmarkdown

write_markdown<-function(quiz_location, setup= "library(tidyverse)"){
  # Handles YAML header and knitr chunk options
  stem<-"---\ntitle: \"T-Tests\"\noutput: learnr::tutorial\nruntime: shiny_prerendered\n---\n```{r setup, include=FALSE}\nlibrary(learnr)\nknitr::opts_chunk$set(echo = FALSE)\n```"
  
  # allows user to specify additional dependencies
  setup<-paste0("```{r, echo = FALSE, message = FALSE}\n", setup, "\nquiz<-read_rds(\"",quiz_location,"\")\n```\n")
  
  # reads quiz and generates items
  quiz<-read_rds(quiz_location)
  n_items<- nrow(quiz$questions)
  item_gen<-map(1:n_items,~ paste0("## Excercise ", 
                                   ., 
                                   "\n`r quiz$questions$parsed_stem[", .,"]`\n", 
                                   "\n`r quiz$questions$parsed_dist[", .,"]`\n", 
                                   "\n`r quiz$questions$parsed_question[", .,"]`\n",
                                   "```{r ex", ., ",exercise=TRUE, exercise.lines = 10}\n\n```"))
  
  
  # Collapses, YAML stem, user setup, and items into one string
  item_gen%>%
    unlist()%>%
    c(stem, setup, .)%>%
    paste(., collapse = "\n")
}